## Heaart-Dicease Dataset

In [150]:
import numpy as np
import pandas as pd

In [151]:
df=pd.read_csv('dataset.csv')
df.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

In [152]:
df.shape

(303, 14)

In [153]:
X=df.iloc[:,0:-1]
y=df.iloc[:,-1]

In [154]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=21)

In [155]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train_scaled = sc.fit_transform(X_train)
X_test_scaled=sc.transform(X_test)

In [156]:
from sklearn.linear_model import LogisticRegression 
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report,precision_score,recall_score,f1_score
lr=LogisticRegression()
dt=DecisionTreeClassifier()
lr.fit(X_train_scaled,y_train)
y_pred1=lr.predict(X_test_scaled)
print("Logistic Regression: ",accuracy_score(y_test,y_pred1))
dt.fit(X_train_scaled,y_train)
y_pred2=dt.predict(X_test_scaled)
print("Decision Tree: ",accuracy_score(y_test,y_pred2))

Logistic Regression:  0.819672131147541
Decision Tree:  0.7704918032786885


In [157]:
confusion_matrix(y_test,y_pred)

array([[27,  5],
       [ 8, 21]], dtype=int64)

In [158]:
print("Logistic Regression Confusion Matrix\n")
pd.DataFrame(confusion_matrix(y_test,y_pred1),columns=list(range(0,2)))

Logistic Regression Confusion Matrix



0   1
0  27   5
1   6  23

In [159]:
print("Logistic Regression Confusion Matrix\n")
pd.DataFrame(confusion_matrix(y_test,y_pred2),columns=list(range(0,2)))

Logistic Regression Confusion Matrix



0   1
0  27   5
1   9  20

In [160]:
print("Precision: ",precision_score(y_test,y_pred))
print("Recall: ",recall_score(y_test,y_pred))
print("F1-Score: ",f1_score(y_test,y_pred))

Precision:  0.8076923076923077
Recall:  0.7241379310344828
F1-Score:  0.7636363636363636


In [161]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.77      0.84      0.81        32
           1       0.81      0.72      0.76        29

    accuracy                           0.79        61
   macro avg       0.79      0.78      0.78        61
weighted avg       0.79      0.79      0.79        61



## Iris Dataset

In [174]:
from sklearn.datasets import load_iris
data=load_iris()

In [175]:
df = pd.DataFrame(data.data,columns=['Sepal_Length','Sepal_Width','Petal_Length','Petal_Width'])

In [176]:
df['target'] = data.target

In [177]:
df.head()

Sepal_Length  Sepal_Width  Petal_Length  Petal_Width  target
0           5.1          3.5           1.4          0.2       0
1           4.9          3.0           1.4          0.2       0
2           4.7          3.2           1.3          0.2       0
3           4.6          3.1           1.5          0.2       0
4           5.0          3.6           1.4          0.2       0

In [178]:
df.shape

(150, 5)

In [179]:
X=df.iloc[:,0:-1]
y=df.iloc[:,-1]

In [180]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=21)

In [181]:
X_train.shape

(120, 4)

In [182]:
from sklearn.linear_model import LogisticRegression 
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report,precision_score,recall_score,f1_score
lr=LogisticRegression()
dt=DecisionTreeClassifier()
lr.fit(X_train,y_train)
y_pred1=lr.predict(X_test)
print("Logistic Regression: ",accuracy_score(y_test,y_pred1))
dt.fit(X_train,y_train)
y_pred2=dt.predict(X_test)
print("Decision Tree: ",accuracy_score(y_test,y_pred2))

Logistic Regression:  0.9333333333333333
Decision Tree:  0.9333333333333333


In [183]:
confusion_matrix(y_test,y_pred1)

array([[11,  0,  0],
       [ 0, 10,  2],
       [ 0,  0,  7]], dtype=int64)

In [184]:
confusion_matrix(y_test,y_pred2)

array([[11,  0,  0],
       [ 0, 10,  2],
       [ 0,  0,  7]], dtype=int64)

In [187]:
print("Precision: ",precision_score(y_test,y_pred1,average='macro'))
print("Recall: ",recall_score(y_test,y_pred1,average='macro'))
print("F1-Score: ",f1_score(y_test,y_pred1,average='macro'))

Precision:  0.9259259259259259
Recall:  0.9444444444444445
F1-Score:  0.9280303030303031


In [188]:
print(classification_report(y_test,y_pred1))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        11
           1       1.00      0.83      0.91        12
           2       0.78      1.00      0.88         7

    accuracy                           0.93        30
   macro avg       0.93      0.94      0.93        30
weighted avg       0.95      0.93      0.93        30



## MNIST Dataset - Softmax Regression

In [189]:
from sklearn.datasets import load_digits
data=load_digits()

In [192]:
X=data.data
y=data.target

In [197]:
from sklearn.linear_model import LogisticRegression
lr=LogisticRegression()
lr.fit(X,y)
y_pred=lr.predict(X)
accuracy_score(y,y_pred)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


1.0

In [199]:
print(confusion_matrix(y,y_pred))

[[178   0   0   0   0   0   0   0   0   0]
 [  0 182   0   0   0   0   0   0   0   0]
 [  0   0 177   0   0   0   0   0   0   0]
 [  0   0   0 183   0   0   0   0   0   0]
 [  0   0   0   0 181   0   0   0   0   0]
 [  0   0   0   0   0 182   0   0   0   0]
 [  0   0   0   0   0   0 181   0   0   0]
 [  0   0   0   0   0   0   0 179   0   0]
 [  0   0   0   0   0   0   0   0 174   0]
 [  0   0   0   0   0   0   0   0   0 180]]


In [200]:
print("Precision: ",precision_score(y,y_pred,average='macro'))
print("Recall: ",recall_score(y,y_pred,average='macro'))
print("F1-Score: ",f1_score(y,y_pred,average='macro'))

Precision:  1.0
Recall:  1.0
F1-Score:  1.0


In [202]:
print(classification_report(y,y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00       178
           1       1.00      1.00      1.00       182
           2       1.00      1.00      1.00       177
           3       1.00      1.00      1.00       183
           4       1.00      1.00      1.00       181
           5       1.00      1.00      1.00       182
           6       1.00      1.00      1.00       181
           7       1.00      1.00      1.00       179
           8       1.00      1.00      1.00       174
           9       1.00      1.00      1.00       180

    accuracy                           1.00      1797
   macro avg       1.00      1.00      1.00      1797
weighted avg       1.00      1.00      1.00      1797

